---
title: "QMD example"
format: html
---

```{r}
library(dplyr); library(knitr); library(kableExtra); 
library(tidyr); library(stringr)
options(knitr.kable.NA = '')
```

Simple table manually generated
```{r}
df <- data.frame(a = c(1, 2), 
                 b = c("[CRAN](https://cran.r-project.org)", "https://github.com"))
knitr::kable(df)
```

My example of an auto generated name
```{r}
hw   <- data.frame(filenames = paste0('hw/', list.files("hw", pattern='template|*.pdf|*.html|*.docx')))

out.hw <- hw %>% mutate(name = gsub("hw/|_template",  "", filenames), 
                          type = str_extract(hw$filenames,".{3}$"),
                          type = ifelse(type=="tml", "html", type),
                          type = ifelse(type=="ocx", "docx", type),
                          nam = gsub(".html|.pdf|.Rmd|.docx", "", name), 
                          link = sprintf("[%s](%s)",type, filenames))

x = out.hw %>% select(link, type, nam) %>% 
    reshape2::dcast(nam~type, value.var="link") %>% 
    kable(format="html", escape=TRUE) %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive" ,"bordered"), 
                  full_width=FALSE,  position = "left")
gsub("<thead>.*</thead>", "", x)
```


```{r}
sessionInfo()
```

